### ISSUE TITLE
Reviewing the La Chouffe DMP - team Don't lock up

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2021-2022#10]
Hi @open-sci/don-t-lock-up,

As anticipated in the [lectures on Thursday](https://docs.google.com/presentation/d/1Y6CdDwgcuQpRJBDbSDDbDBXULCWljCGSnsgn_FU0hPs/edit#slide=id.gd0ba9f17f0_0_142), two of you have to review the [DMP developed by the team La Chouffe](https://github.com/open-sci/2021-2022/issues/5). The two people selected for addressing this task must work independently writing a review and must publish it on [Qeios](https://www.qeios.com/), in order to get a DOI for it. A reminder: once the review is published and a DOI is obtained, the review cannot be modified anymore.

Once both your reviews are published, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of both the reviews.

For further doubts, do not hesitate to contact me in the Slack group.

**Comment by umut-kucuk** [comment]
Hi, here is my review for the La Chouffe DMP, https://doi.org/10.32388/PP47IN

**Comment by chiarasharp** [comment]
Hello, here is my review of the La Chouffe DMP: [https://doi.org/10.32388/KSPWTZ](https://doi.org/10.32388/KSPWTZ).
