### ISSUE TITLE
Reviewing the Don't lock up protocol - team La Chouffe

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2021-2022#11]
Hi @open-sci/la-chouffe,

As anticipated in the [one of the previous lectures](https://docs.google.com/presentation/d/1Y6CdDwgcuQpRJBDbSDDbDBXULCWljCGSnsgn_FU0hPs/edit#slide=id.gd0ba9f17f0_0_142), two of you (or one, in case you are a group of three people, and two of them have already reviewed a DMP) have to review the [protocol developed by the team Don't lock up](https://github.com/open-sci/2021-2022/issues/8). The people selected for addressing this task must work independently writing a review and must publish it on [Qeios](https://www.qeios.com), in order to get a DOI for it. A reminder: once the review is published and a DOI is obtained, the review cannot be modified anymore.

Once both your reviews are published, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of the reviews.

For further doubts, do not hesitate to contact me in the Slack group.

**Comment by ChiaraCati** [comment]
Hi, [here](https://www.qeios.com/read/IDM7UP) is my peer-review on team DonTLockUp protocol
