### ISSUE TITLE
Revised version of DMP - team La Chouffe

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2021-2022#15]
Hi @open-sci/la-chouffe,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1QFTaIfCRATf8EFRvanRz67U4xHpb8zw5FUeEpSwJd20/edit?usp=sharing), you have to revise your Data Management Plan (DMP) published on Zenodo according to the reviews received by the members of the other team. The revision of the DMP must be done using an existing service, i.e. [OpenAIRE Argos](https://argos.openaire.eu/). Once your revision of the DMP is finalised, please deposit it in Zenodo (by adding appropriate metadata) in at least a machine-readable format (e.g. JSON) and PDF.

In addition, you must also write and publish a response letter to the reviewers, where you explain either how you have addressed their comments or the justification for not having addressed them (please remember that if the latter applies, then your justifications must be very robust). Once finalised, the response letter must be published in Zenodo, and it should explicitly link and mention (even in the metadata) the reviews received, the old version of the DMP and the revised one.

Then, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of the revision of the DMP and of the response letter. The deadline to provide all this information is the 27th of April.

For further doubts, do not hesitate to contact me in the Slack group.

**Comment by dbrembilla** [comment]
Here is the revised version for the DMP: [doi:10.5281/zenodo.6480484](https://zenodo.org/record/6480484)

**Comment by GiuliaVenditti** [comment]
Here is the revised version for the DMP together with the response letter: https://doi.org/10.5281/zenodo.6491625
