### ISSUE TITLE
Submitting the software - team Don't lock up

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2021-2022#16]
Hi @open-sci/don-t-lock-up ,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1LHPGt18AhFF-VkzQljlsiADWCnWvzy-I6ZoMDNtJMqo/edit#slide=id.gcd92ad6878_0_3), once finalised, the [software you developed](https://github.com/open-sci/2021-2022-don-t-lock-up-code) must be assigned with a DOI via Zenodo.

Once in Zenodo, close this issue by attaching in the comment the clickable DOI URL (https://doi.org/...) of the software. The version specified here must be also the one cited in the research article to write.

For further doubts, do not hesitate to contact me in the Slack group.

**Comment by chiarasharp** [comment]
Here is our final sw:
> Constance Dami, Chiara Manca, Alessandro Bertozzi, & Umut Kucuk. (2022). Coverage of DOAJ journals' citations through OpenCitations - Software (Version 1). Zenodo. [https://doi.org/10.5281/zenodo.6573898](https://doi.org/10.5281/zenodo.6573898)
