### ISSUE TITLE
Submitting the software - team La Chouffe

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2021-2022#17]
Hi @open-sci/la-chouffe,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1LHPGt18AhFF-VkzQljlsiADWCnWvzy-I6ZoMDNtJMqo/edit#slide=id.gcd92ad6878_0_3), once finalised, the [software you developed](https://github.com/open-sci/2021-2022-la-chouffe-code) must be assigned with a DOI via Zenodo.

Once in Zenodo, close this issue by attaching in the comment the clickable DOI URL (https://doi.org/...) of the software. The version specified here must be also the one cited in the research article to write.

For further doubts, do not hesitate to contact me in the Slack group.

**Comment by dbrembilla** [comment]
Hello,
Please find at this DOI the software we used for our research: 10.5281/zenodo.6569370
