### ISSUE TITLE
Submitting the presentation - team Don't lock up

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2021-2022#20]
Hi @open-sci/don-t-lock-up,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1USObdYTaujrTikkRtqZlJ8zXh3C91dBezCxdTuskvi4/edit#slide=id.gd3972084b6_0_0), once finalised, the slides supporting your presentation must be uploaded on Zenodo, in order to get a DOI to refer to them, by the 09:00 of the 25th of May.

Once in Zenodo, close this issue by attaching in the comment the clickable DOI URL (https://doi.org/...) of the slides. Please remind to specify, in the title slide (the very first one), all the members of the group and the related roles each member has had in the context of the project, using the [CRediT – Contributor Roles Taxonomy](https://casrai.org/credit/), accompany each of the roles with a brief description of what has been done.

For further doubts, do not hesitate to contact me in the Slack group.

**Comment by AlessandroBertozzi** [comment]
Here there is the link for the presentation: https://doi.org/10.5281/zenodo.6579115
