### ISSUE TITLE
Creation of material.md - team La Chouffe

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2021-2022#23]
Hi @open-sci/la-chouffe,

As anticipated in [one of the previous lectures)](https://docs.google.com/presentation/d/1USObdYTaujrTikkRtqZlJ8zXh3C91dBezCxdTuskvi4/edit#slide=id.gd3972084b6_0_0), in the [space dedicated to your group](https://github.com/open-sci/2021-2022/tree/main/docs/LaChouffe) in the repository of the course, you have to create a [`material.md`](https://github.com/open-sci/2021-2022/tree/main/docs/LaChouffe/material.md) file where you list all the members of the group with all the roles they have had in the project (using the [CRediT taxonomy](https://casrai.org/credit/) as specified in the title page of your slides). 

In addition, in the `material.md` file, you also need to add a bibliographic reference in APA style for each of the items to submit. You can follow the template below to create the document (the words between angular brackets must be substituted with the correct value):

```
# Material - team <<name of the team>>

## Members
[<<Member 1 full name>>](<<GitHub account URL>>), roles:
* <<role 1>>, <<description 1>>
* <<role 2>>, <<description 2>>
* ...

[<<Member 2 full name>>](<<GitHub account URL>>), roles:
* <<role 1>>, <<description 1>>
* <<role 2>>, <<description 2>>
* ...

[<<Member 3 full name>>](<<GitHub account URL>>), roles:
* <<role 1>>, <<description 1>>
* <<role 2>>, <<description 2>>
* ...

[<<Member 4 full name>>](<<GitHub account URL>>), roles:
* <<role 1>>, <<description 1>>
* <<role 2>>, <<description 2>>
* ...


## Material

### Data Management Plan
<<Bibliographic reference in APA style of the last version>>

Reviews of the [<<initial version of the DMP>>](<<DOI URL of the initial version of the DMP>>):
* <<Bibliographic reference in APA style of the first review>>
* <<Bibliographic reference in APA style of the second review>>

Authors' response to the reviews:
* <<Bibliographic reference in APA style of the authors' response to the reviews>>


### Protocol introducing the methodology
<<Bibliographic reference in APA style of the last version>>

Reviews of the [<<initial version of the protocol>>](<<DOI URL of the initial version of the protocol>>):
* <<Bibliographic reference in APA style of the first review>>
* <<Bibliographic reference in APA style of the second review>>

Authors' response to the reviews:
* <<Bibliographic reference in APA style of the authors' response to the reviews>>


### Software developed
<<Bibliographic reference in APA style of the last version>>


### The data gathered while running the methodology
<<Bibliographic reference in APA style of the last version>>


### Article presenting the research
<<Bibliographic reference in APA style of the last version>>


### Slides supporting the presentation
<<Bibliographic reference in APA style of the last version>>
```

Please remember that the last point (i.e. "Slides supporting the presentation") can be added **after** the workshop on the 25th of May. 

For further doubts, do not hesitate to contact me in the Slack group.

**Comment by dbrembilla** [comment]
Hello,
Please find our materials.md in our directory in this repository : https://github.com/open-sci/2021-2022/blob/main/docs/LaChouffe/materials.md
