### ISSUE TITLE
Updating the abstract - team Don't lock up

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2021-2022#24]
Hi @open-sci/don-t-lock-up,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1QFTaIfCRATf8EFRvanRz67U4xHpb8zw5FUeEpSwJd20/edit?usp=sharing), you have to update the abstract you wrote and uploaded in the GitHub repository of the course with more precise and additional information derived from the study you have conducted so far (which includes also the information collected in the DMP and in the protocol).

Once finalised, the abstract must be included in the research article you have to prepare and submit it by the 23rd of May, 23:59 Rome time. However, please update the abstract before writing the article, and every time you have either new or more precise information to share.

For further doubts, do not hesitate to contact me in the Slack group.

**Comment by chiarasharp** [comment]
The final abstract can be found in our docs folder.
