### ISSUE TITLE
Revised version of the protocol - team Don't lock up

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2021-2022#26]
Hi @open-sci/don-t-lock-up,

As anticipated in [one of the previous lectures (practical part)](https://docs.google.com/presentation/d/1QFTaIfCRATf8EFRvanRz67U4xHpb8zw5FUeEpSwJd20/edit?usp=sharing), you have to revise your protocol published on Protocols.io according to the reviews received by the members of the other team. Once your revision of the workflow is finalised, please publish it using the Protocols.io interface. 

In addition, you must also write and publish a response letter to the reviewers, where you explain either how you have addressed their comments or the justification for not having addressed them (please remember that if the latter applies, then your justifications must be very robust). Once finalised, the response letter must be published in Zenodo, and it should explicitly link and mention (even in the metadata) the reviews received, the old version of the protocol and the revised one.

Then, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of the revision of the protocol and of the response letter. The deadline to provide all this information is the 9th of May.

For further doubts, do not hesitate to contact me in the Slack group.

**Comment by chiarasharp** [comment]
Here is our rebuttal letter:

> Constance Dami, Chiara Manca, Alessandro Bertozzi, & Umut Kucuk. (2022). Rebuttal letter to the review of "Coverage of open citations in DOAJ journals (Protocol)". [https://doi.org/10.5281/zenodo.6533180](https://doi.org/10.5281/zenodo.6533180)

And here is our new version of the protocol:

> Constance Dami, Alessandro Bertozzi, Chiara Manca, Umut Kucuk 2022. Coverage of open citations in DOAJ journals - Protocol. protocols.io
[https://dx.doi.org/10.17504/protocols.io.n92ldz598v5b/v3](https://dx.doi.org/10.17504/protocols.io.n92ldz598v5b/v3)
Version created by [Chiara Manca](https://www.protocols.io/researchers/chiara--manca)
