### ISSUE TITLE
Reviewing the Don't lock up DMP - team La Chouffe

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2021-2022#9]
Hi @open-sci/la-chouffe,

As anticipated in the [lectures on Thursday](https://docs.google.com/presentation/d/1Y6CdDwgcuQpRJBDbSDDbDBXULCWljCGSnsgn_FU0hPs/edit#slide=id.gd0ba9f17f0_0_142), two of you have to review the [DMP developed by the team Don't lock up](https://github.com/open-sci/2021-2022/issues/6). The two people selected for addressing this task must work independently writing a review and must publish it on [Qeios](https://www.qeios.com/), in order to get a DOI for it. A reminder: once the review is published and a DOI is obtained, the review cannot be modified anymore.

Once both your reviews are published, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of both the reviews.

For further doubts, do not hesitate to contact me in the Slack group.

**Comment by dbrembilla** [comment]
Here is my DMP review for the DMP made by the group La Chouffe: https://doi.org/10.32388/N2Q3S8

**Comment by GiuliaVenditti** [comment]
Hi @essepuntato,

Here is my DMP review: https://www.qeios.com/read/1J0YCK

**Comment by GiuliaVenditti** [comment]
Hi @essepuntato,

Here is my DMP review: https://doi.org/10.32388/1J0YCK
